### ISSUE TITLE
Redraw sometimes isn't triggered at end of data set

### ISSUE THREAD

**Issue by DaveDuchene** [DataTables/Scroller#40]
Since nobody else is complaining about this, my guess that this is happening to us due to the various ways that we're abusing/misusing DataTables (simulating infinite scroll, using fixed columns, sizing through CSS).

As the subject line says, when we scroll to the bottom of our virtual area, a redraw isn't triggered. Fixed in the attached PR.

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please?

**Comment by DataTables** [comment]
Closing in favour of #41.
