### ISSUE TITLE
API does not return all rows when using scroller and data option

### ISSUE THREAD

**Issue by jakezatecky** [DataTables/Scroller#42]
I am having an issue where the API method `.rows().nodes()` does not return all of the rows that are associated with the table when `deferRender` is `true` and I am using the `data` option:

``` javascript
$("#table").dataTable({
    dom: "frtiS",
    deferRender: true,
    scrollY: "150px",
    data: data,
    initComplete: function() {
        // Does not return all rows
        $("span").html($("#table").DataTable().rows().nodes().length);
    }
});
```

This issue appears to **only** occur if using `deferRender`, `scrollY`, and `data`. If I store the table data in the DOM, then the correct number of rows are returned. If I do not use `scrollY`, then the correct number of rows are return.

See the following jsFiddle where a DataTable is loaded according to the configuration above. 5000 rows are loaded into the table, but DataTables incorrectly states hat only 45 nodes exist:

http://jsfiddle.net/8dqfcr6t/1/

Any ideas how to mitigate this issue? Tested on Firefox and Chrome.

**Comment by DataTables** [comment]
Actually the issue should only be due to the `deferRender` tag. The whole point of `deferRender` is that the nodes are not created until they are returned by the draw. If you need all rows (what for?) then you would need to remove the deferRender option, which mitigates any performance benefit you might get from using it and Scroller.

**Comment by jakezatecky** [comment]
Yeah, I don't know what I was thinking.

I need the entire set of rows because the user is able to "select all" rows and selectively deselect any undesired rows.
