### ISSUE TITLE
License info in bower.json

### ISSUE THREAD

**Issue by ricardobarone** [DataTables/Scroller#51]
Please add a `license` key to `bower.json`. It's required by some deployment tools, like [webjars](http://www.webjars.org/bower).

And thanks for this great library!

**Comment by DataTables** [comment]
Thanks for pointing this out. I'm needing to go through all of the repos and update the various files for the package managers. I'll make sure this is done when I do that, which hopefully won't be far away.

**Comment by DataTables** [comment]
Finally done :-). I'd recommend using the [distribution repos](//datatables.net/blog/2015-11-09) when using DataTables and its extensions with bower rather than the source repos such as this one.
