### ISSUE TITLE
scroller 1.3 new init overwrites column widths when no content

### ISSUE THREAD

**Issue by the86freak** [DataTables/Scroller#54]
when using scroller 1.3 it ignores the column width when there's no content in the table.

after adding content the columns are displayed with the correct width.
But using table.draw() or even table.draw('page') resets the column width again then.

This doesn't occur when using 1.2.2.

Any idea how to debug?

**Comment by DataTables** [comment]
I'm not sure what would cause that. Can you link to a test page showing the issue?

**Comment by the86freak** [comment]
thanks for your really fast answer.
I can't reproduce with a basic config:
http://jsfiddle.net/The86Freak/u9y7evve/

I guess it has something to do with this resize-plugin:

https://github.com/Silvacom/colResize
I got rid of it and it worked then. Thanks again for your help and the great product!
