### ISSUE TITLE
Disable Length Menu

### ISSUE THREAD

**Issue by joekeen** [DataTables/Scroller#55]
The Length Menu does not play well with the Scroller.

![screen shot 2015-09-01 at 8 11 50 pm](https://cloud.githubusercontent.com/assets/1745655/9601558/c0636482-50e5-11e5-8535-0b7dc9ffad52.png)

I have disabled it with the [lengthChange](https://datatables.net/reference/option/lengthChange) option. 

```javascript
$('#example').dataTable( {
  "lengthChange": false
} );
```

Just wondering if it should be disabled by default when the Scroller extension is in use.

**Comment by DataTables** [comment]
Probably yes. Scroller will override the length that is set anyway.
