### ISSUE TITLE
No horizontal scrolling in header cols

### ISSUE THREAD

**Issue by HendrikAnnighoefer** [DataTables/Scroller#59]
If the table has an overflow a horizontal scrollbar appears for the content (that's ok). But because of the separation of scrollHead and scrollBody, you can just scroll the body so the cols are not in the right allignment any more. 

Here is an example: http://jsfiddle.net/9ezfcvyx/3/
Testet in Firefox/IE

**Comment by DataTables** [comment]
You need to enable `scrollX` if there is horizontal scrolling.
