### ISSUE TITLE
deferLoading 'ignored' when using Scroller

### ISSUE THREAD

**Issue by jbrichau** [DataTables/Scroller#63]
I am using Datatables 1.10.11 with Scroller 1.4.1 and loading the data via server-side processing. Since I want my users to only see rows when they explicitly enter a search query, I am trying to use the deferLoading option. This works fine except when I'm using Scroller. It seems that Scroller triggers a draw of the table on initialisation, which triggers a load of the data on the server.

I made a JsFiddle demonstrating the issue: https://jsfiddle.net/jbrichau/gdLr4vmp/
In the fiddle, you see that the table is immediately filled with data. However, it should only be filled when you hit the reload button.

I also started fiddling around in the Scroller source, and noticed how a call to fnMeasure on init triggers a draw of the table. Changing the code on this line: https://github.com/DataTables/Scroller/blob/master/js/dataTables.scroller.js#L590 to that.fnMeasure(false); fixed my problem. However, I'm unsure of this is the way to go or not.

ps: Also posted this last friday on the forum: https://datatables.net/forums/discussion/33774/datatables-with-scroller-and-server-side-processing-with-deferloading-still-loads-data-on-table-init (not to pressure, but I was not sure if issues like this should be here or on the forum)

**Comment by DataTables** [comment]
Thanks for flagging this up. Let's do it in the forum only rather than duplicating the discussion. I'll reply back there when I've had a chance to look at this issue.
