### ISSUE TITLE
Header row doesn't adjust

### ISSUE THREAD

**Issue by MollyWing** [DataTables/Scroller#65]
When viewing a scroller table, the heading does not automatically re-adjust if a user re-sizes the page. However, this issue will resolve if a user clicks to sort a column or refresh.

![image](https://cloud.githubusercontent.com/assets/20586348/17040151/e699a8a0-4f63-11e6-8dae-fa0256bdf7e6.png)

**Comment by DataTables** [comment]
Can you post your question in the [DataTables forums](//datatables.net/forums) with a link to a test page showing the issue so it can be debugged please?

My guess is that you either need to add `width="100%"` to your `<table>`, or if you prefer, call `columns.adjust()` when the browser is resized (adding `width="100%"` makes that happen automatically).

**Comment by MollyWing** [comment]
width="100%" resolved the issue, thank you for your help!
