### ISSUE TITLE
Scroller does not work with i18n

### ISSUE THREAD

**Issue by yihui** [DataTables/Scroller#67]
When using the Scroller extension and the `language` option on a table, there will be a JS error

```
jquery.dataTables.min.js:55 Uncaught TypeError: Cannot read property 'style' of undefined
```

The initialization options:

```json
{
  "language": {
    "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Slovak.json"
  },
  "scroller": true
}
```

An output example: [test.html.zip](https://github.com/DataTables/Scroller/files/423684/test.html.zip)

**Comment by DataTables** [comment]
Seems to work without issue here: http://live.datatables.net/huvoleko/1/edit .

Can you give a link to a test case showing the issue using the resources on the CDN please. I'm not sure what file is what in the base64 used in the attached file.

**Comment by yihui** [comment]
Sure. Here is a test case based on your example: http://live.datatables.net/huvoleko/3/edit

**Comment by DataTables** [comment]
Thanks for the test case. 

Your example doesn't work because the use of `language.url` makes the table init async. 

From [its documentation](https://datatables.net/reference/option/language.url):

> Note that when this parameter is set, DataTables' initialisation will be asynchronous due to the Ajax data load. That is to say that the table will not be drawn until the Ajax request as completed. As such, any actions that require the table to have completed its initialisation should be placed into the `initComplete` callback.

That is exactly what you need to do here - use the API in `initComplete`: http://live.datatables.net/huvoleko/4/edit

**Comment by yihui** [comment]
Great. Thanks for the help!
