### ISSUE TITLE
Binding scroller with mCustomScrollbar()

### ISSUE THREAD

**Issue by wwwizzarrdry** [DataTables/Scroller#70]
Anyone have any success using scroller with the mCustomScrollbar plugin? I'm not sure which scroller event to bind to in order to update the page/table record info properly.

Basically, it seems like mCustomScrollbar +scroller work fine together, scroller just doesn't see the scroll event when the custom scroller is initialized, therefore the table record info doesn't update on when scrolling.

**Comment by DataTables** [comment]
As long as it triggers the `scroll` event on the scrolling element, it should work. I'm not sure how mCustomScrollbar works though - does it just put a div in a div and scroll them without OS provided scrollbars? Going to close for the moment as this doesn't appear to be a bug.
