### ISSUE TITLE
 Drag to the end, dynamically generate serial error, the first column 

### ISSUE THREAD

**Issue by 49839013** [DataTables/Scroller#73]
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<title></title>
		
    
   
   
	<script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/scroller/1.4.3/js/dataTables.scroller.min.js"></script>
	</head>

	<body style="overflow:hidden;">
<table id="example" class="stripe row-border order-column nowrap" width="100%" cellspacing="0">
        <thead>
            <tr> 
                <th>ID</th>
                <th>First name</th>
                <th>Last name</th>
                <th>ZIP / Post code</th>
                <th>Country</th>
            </tr>
        </thead>
    </table>
	</body>
<script>
	
	
	$(document).ready(function() {
        var data = [];
        for ( var i=0 ; i<50000 ; i++ ) {
            data.push( [ 0, i, i, i, i ] );
        }
         
        $('#example').DataTable( {
            data:           data,
            deferRender:    true,
            scrollY:        200,
            scrollCollapse: true,
            scroller:       true,
			        "drawCallback": function() { 
		　this.api().column(0).nodes().each(function(cell, i) {
		        　　　　cell.innerHTML =  i + 1;
		        　　});
        },
        } );
    } );
	</script>

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please.

**Comment by DataTables** [comment]
Going to close this for now as no test case is provided and I've not been able to replicate the issue. Please reopen with a test case if this is still a problem.
