### ISSUE TITLE
<object> tag in IE

### ISSUE THREAD

**Issue by mmuruev** [DataTables/Scroller#74]
Plugin uses <object> for background scroll frame it works fine for Chrome and Firefox, but in IE I have border around this element. After some experiments found that it has something to do with data='about:blank'.

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please? [This example of Scroller](https://datatables.net/extensions/scroller/examples/initialisation/simple.html) doesn't use an `object` tag, nor does it do so in its code.

**Comment by mmuruev** [comment]
Yes my bad this is pageResize plugin.

**Comment by DataTables** [comment]
Thanks for the clarification. You are correct - the pageResize [currently uses an `object` tag](https://github.com/DataTables/Plugins/blob/389a9890602f00d47c1e007b9888bec3f235755c/features/pageResize/dataTables.pageResize.js#L110).

At some point I'll update it to use an `iframe` instead, which is what the [`scrollResize` plug-in does](https://github.com/DataTables/Plugins/blob/389a9890602f00d47c1e007b9888bec3f235755c/features/scrollResize/dataTables.scrollResize.js#L96).

That is actually likely to be built into the next major version of DataTables - with an iframe.
