### ISSUE TITLE
Scroller wrong `types` and no `module` field

### ISSUE THREAD

**Issue by sadeghbarati** [DataTables/Scroller#94]
@AllanJard sry for directive mention again,

I found issue in `datatables.net-scroller v2.0.7`, however it's strange that [`Dist-DataTables-Scroller`](https://github.com/DataTables/Dist-DataTables-Scroller) repo is updated

When I try to install latest version of `datatables.net-scroller`, in node_modules it' still:

- using `declare namespace DataTables` instead of `declare module 'datatables.net'`
- There is no `dataTables.scroller.mjs` or `dataTables.scroller.min.mjs` file in js folder

![image](https://user-images.githubusercontent.com/17789047/202898302-e1d82d08-1f6b-4d13-a65a-6eb04320d921.png)

**Comment by AllanJard** [comment]
Sorry about that! I missed Scroller while I was going through and tagging up everything else. That's 2.1.0 released now.
